### ISSUE TITLE
Solution Turmrechnen

### ISSUE THREAD

**Issue by SimonPrimetzhofer** [rstropek-teaching/turmrechnen-quiz-4ahif-SimonPrimetzhofer#1]
Dear Mr. Stropek!

Here is the link to my solution:
https://stackblitz.com/edit/angular-eq1vj2

Greetings,
Simon Primetzhofer

**Comment by rstropek** [comment]
Nearly. Result is not a table (i.e. not formatted as shown in the specification). Everything else works as expected.

Greetings,
Rainer Stropek.

**Comment by SimonPrimetzhofer** [comment]
Dear Mr. Stropek!

I just changed the output of the result to be displayed in a table.

Greetings,
Simon Primetzhofer

**Comment by rstropek** [comment]
Not a valid table yet ;-) `td` tags missing and alignment is not as shown in the specs.

**Comment by SimonPrimetzhofer** [comment]
Ok... I hope it is okay now :)

**Comment by rstropek** [comment]
Perfekt. Your extra point is secured. Just one comment: Why didn't you use a `for` loop in `towerLogic`?

Greetings,
Rainer Stropek.
